### ISSUE TITLE
only works with a single QR Code export

### ISSUE THREAD

**Issue by oliverbaush** [krissrex/google-authenticator-exporter#14]
Might be worth mentioning in the REAMDE that the QR code presented by Google Auth must not be more than one. 

In case it is more than one the workaround is to limit the amount of exported accounts

**Comment by mistval** [comment]
If you have more than one QR code, you can scan each one, then run each URL through the script separately.

**Comment by krissrex** [comment]
No, this should work up to the maximum of 10 accounts per QR code. Make sure your QR decoder is able to decode such large QRs.

Let me know if you still have issues.
