### ISSUE TITLE
Module index.js not found

### ISSUE THREAD

**Issue by Trop-ix** [krissrex/google-authenticator-exporter#21]
I was just testing the code when i stumbled upon an 'error'.
It occurs whenever i try to run 'npm run start' or 'npm run start:qrcode' 

npm and Nodejs are installed. and the index.js file exists in the stated location...

Am i doing something wrong/missing something, or what could be the problem here?

> ** Enviroment **
> Debian 12 Virtual Machine running in Virtual Box

> ** Error Message **
> 
> npm run start
> 
> google-auth-exporter@1.0.0 start
> node ./src/index.js
> 
> node:internal/modules/cjs/loader:1042
>  throw err;
>   ^
>
> Error: Cannot find module 'prompt'
> Require stack:
> - /home/vm-admin/Downloads/google-authenticator-exporter-master/src/index.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
>     at Module._load (node:internal/modules/cjs/loader:885:27)
>     at Module.require (node:internal/modules/cjs/loader:1105:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at promptUserForUri (/home/vm-admin/Downloads/google-authenticator-exporter-master/src/index.js:136:18)
>     at Object.<anonymous> (/home/vm-admin/Downloads/google-authenticator-exporter-master/src/index.js:190:1)
>     at Module._compile (node:internal/modules/cjs/loader:1218:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
>     at Module.load (node:internal/modules/cjs/loader:1081:32)
>     at Module._load (node:internal/modules/cjs/loader:922:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/vm-admin/Downloads/google-authenticator-exporter-master/src/index.js'
>   ]
> }
> 
> Node.js v18.13.0

**Comment by AngaBlue** [comment]
Looks like you haven't installed dependencies with `npm i`.

**Comment by ruscon** [comment]
> Looks like you haven't installed dependencies with `npm i`.

better to run
```shell
npm ci
```

**Comment by krissrex** [comment]
Yeah, you need to run `npm install` as suggested above.
