### ISSUE TITLE
Not available with the new app

### ISSUE THREAD

**Issue by tjw123hh** [krissrex/google-authenticator-exporter#23]
Google now use a single QR code to store all the keys you've chosen to export, so it is now not available.

**Comment by tjw123hh** [comment]
![图片](https://github.com/krissrex/google-authenticator-exporter/assets/56749271/d98f0b08-1584-4c72-8bd3-7bf85571050e)

**Comment by krissrex** [comment]
Oh, thank you! I have had little time to look at hobby projects lately, but this seems like a breaking change from Google. I might have to fix this.

**Comment by krissrex** [comment]
I made a test case, and used Google Authenticator version `6.0` to generate new QR exports. It seems to still work.

What version of the app have you installed? If you long-press the app icon in the app list, select "info" or  ( :information_source: ) icon, and then scroll all the way to the bottom, it should display the version.

**Comment by krissrex** [comment]
Also, how many accounts (approximately) were you tring to export? When I tried with 12, it exported as 2 QR codes with 10 and 2.

**Comment by krissrex** [comment]
I notice that my app exported the protobuf using format version 1, and I see the app supports a version 2. Not sure why it exported as version 1. Also cannot find evidence of the app ever exporting as version 2.

I added an error log in [5a357cc](https://github.com/krissrex/google-authenticator-exporter/commit/5a357cc946d0f07d72064d43f048c110e2868dde) in case anyone tries to decode version 2.

**Comment by tjw123hh** [comment]
It seems that it works fine now. I'm closing this issue.

**Comment by BosieIonut** [comment]
Hello, i get this error exported from iPhone, google authentificator app, exported only 1 code.
`Expected payload version 1, but was 2! Please comment your payload version (which is 2), Google Authenticator app version and how many 2FA codes you exported in https://github.com/krissrex/google-authenticator-exporter/issues/23 .`

what can i do?

**Comment by krissrex** [comment]
> what can i do?

Thanks for letting me know! If you can't find a way of exporting version 1 format, I will have to add support for version 2.

I think version 2 exists in https://github.com/beemdevelopment/Aegis/blob/master/app/src/main/proto/google_auth.proto , so I can update using that

**Comment by falkgeist** [comment]
As stated in #26, this seems to be working, just maybe remove the warning (or only show it when export actually failed).
